AWSTemplateFormatVersion: "2010-09-09"
Description:
Parameters:
  ASGName:
    Type: String
    Description: "Auto Scaling Group Name"
  VPCZoneIdentifier:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "List the Subnet Ids of the instances"

Resources:
  AutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Ref ASGName
      DesiredCapacity: String
      HealthCheckGracePeriod: Integer
      HealthCheckType: String
      LaunchConfigurationName: String
      LaunchTemplate:
        LaunchTemplateSpecification
      LifecycleHookSpecificationList:
        - LifecycleHookSpecification
      LoadBalancerNames:
        - String
      MaxSize: String
      MetricsCollection:
        - MetricsCollection
      MinSize: String
      MixedInstancesPolicy:
        MixedInstancesPolicy
      NotificationConfigurations:
        - NotificationConfiguration
      PlacementGroup: String
      ServiceLinkedRoleARN: String
      Tags:
        - TagProperty
      TargetGroupARNs:
        - String
      TerminationPolicies:
        - String
      VPCZoneIdentifier: !Ref VPCZoneIdentifier