language: go

go:
  - 1.11.x
  - master

services:
  - docker

before_install:
  - docker run -d -p 5080:5080 -p 6080:6080 -p 9080:9080 --name dgraph dgraph/dgraph dgraph zero
  - docker exec -d dgraph dgraph alpha --lru_mb 4096 --zero localhost:5080


script: go test -v ./...