language: go

go:
  - 1.11.x
  - master

services:
  - docker

before_install:
  - docker-compose -f test/dgraph-compose.yaml up &


script:
  - go test -v -coverprofile=app.txt -covermode=atomic ./app/...
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./app/...
  - cat app.txt >> coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)