language: go

go:
  - 1.11.x
  - master

services:
  - docker

before_install:
  - docker-compose -f docs/dgraph-test-compose.yaml up &


script:
  - go test -v -coverprofile=api.txt -covermode=atomic ./api/...
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./service/...
  - cat api.txt >> coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)