[database]

  [[database.connections]]
    host = "localhost"
    port = 9080

  [[database.connections]]
    host = "localhost"
    port = 9080

[general]
  max_goroutines = 0
  port = 8002
  log_level = "info"