[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/dgraph-io/dgo"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stevenayers/clamber"
  branch = "master"
