[database]

  [[database.connections]]
    host = "localhost"
    port = 9080


[general]
  max_goroutines = 0
  port = 8888
  log_level = "info"
  http_retry_attempts = 5
  http_back_off_duration = 2